// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TsType } from "./TsType";

export interface TsArg {
  name: string;
  ty: TsType;
}
