// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TsArg } from "./TsArg";
import type { TsType } from "./TsType";

export type TsFunc = { name: string; args: Array<TsArg>; ret: TsType };
